#!/bin/bash -e

## USAGE: ./run-openmrs-docker "<mariadb/mysql>"

set -x
source common.sh

# docker image/type of database
# Tested with mysql and mariadb
export DB_DATABASE_TYPE="$1"

export DB_DOCKER_IMAGE="$DB_DATABASE_TYPE"
export DB_DOCKER_NAME="${DB_DOCKER_IMAGE}-${BAMBOO_BUILDNUMBER}"

export OPENMRS_DOCKER_IMAGE="openmrs-${DB_DATABASE_TYPE}"
export OPENMRS_DOCKER_NAME="${OPENMRS_DOCKER_IMAGE}-${BAMBOO_BUILDNUMBER}"

export SHELLOPTS

start_db_docker() {
  echo "Starting docker container named ${DB_DOCKER_NAME} of image ${DB_DOCKER_IMAGE}"
  # create docker container for database
  DB_DOCKER_PID=$(docker run --name "$DB_DOCKER_NAME" \
  -e MYSQL_ROOT_PASSWORD=openmrs -e MYSQL_USER=test \
  -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=openmrs-${BAMBOO_BUILDNUMBER} -d ${DB_DOCKER_IMAGE})

  sleep 15
  echo "------------"
  docker logs ${DB_DOCKER_PID}
  echo "------------"

  echo "${DB_DOCKER_NAME} docker container should now be up and running"
}

build_openmrs_docker_image() {
  echo "Building the openmrs docker image"
  docker build --rm=true -t ${OPENMRS_DOCKER_IMAGE}:latest .
  echo "${OPENMRS_DOCKER_IMAGE} image built"
}

run_openmrs_docker_container() {
  echo "Starting docker container named ${OPENMRS_DOCKER_NAME} of image ${OPENMRS_DOCKER_IMAGE}"

  DC_ID=$(docker run -d --name ${OPENMRS_DOCKER_NAME} \
  --link ${DB_DOCKER_NAME}:${DB_DOCKER_IMAGE} \
  -p 8080:8082 \
  ${OPENMRS_DOCKER_IMAGE})

  sleep 20

  echo "------------"
  docker logs ${DC_ID}
  echo "------------"
  docker info
  docker ps
  echo "------------"

  echo "${OPENMRS_DOCKER_NAME} docker container should now be up and running"

}

smoke_test_openmrs() {
  for COUNT in {1..5}
  do
    if ! wget --spider http://localhost:8082/openmrs; then
      docker ps
      echo "Sleeping 10 seconds"
      sleep 10
    else
      echo "Server up!"
      return
    fi
  done
  echo "------------"
  docker logs ${DC_ID}
}

cleanup
start_db_docker
build_openmrs_docker_image
run_openmrs_docker_container
smoke_test_openmrs
exit 0
